### PR TITLE
Handle empty RootNamespace

### LINKED ISSUE #5: Attempt to set RootNamespace to empty is failing
It turns out that the .NET Core SDK does this:

```xml
<RootNamespace Condition=" '$(RootNamespace)' == '' ">$(MSBuildProjectName)</RootNamespace>
```
and it does that after our `.props` files load, so that has the effect of overwriting our attempts to set it to be empty.

Investigate whether it's possible for us to make this happen later in the process, but if not, remove the relevant lines from this package since it doesn't have any useful effect.

### PR DESCRIPTION
**Pull request by idg10**
Resolves #5

### CODE REVIEW

**Comment by HowardvanRooijen** [comment]
Can we point to where the nuget package is available from / where the CI/CD pipeline is?

**Comment by idg10** [comment]
> Can we point to where the nuget package is available from / where the CI/CD pipeline is?

We already do:

https://github.com/endjin/Endjin.RecommendedPractices.NuGet/#packages

https://github.com/endjin/Endjin.RecommendedPractices.NuGet/#ci--cd

**Comment by HowardvanRooijen** [comment]
I meant in the ADR - i.e. it would be nice to actually link to the package.

**Comment by idg10** [comment]
@HowardvanRooijen ah, got you. Pushed a commit linking to the NuGet package. It is not at all obvious to me where a link to the CI/DI pipeline belongs in the ADR.

**Pull request merged**
